{
 "title": "productive",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "loki_query",
    "label": "Loki Query",
    "query": "job=~\"pm2.*|jenkins-build\"\\,filename!=\"/var/lib/deploy/.pm2/logs/invoice-jar-error.log\",\njob=~\"pm2.*\"\\,filename!=\"/var/lib/deploy/.pm2/logs/invoice-jar-error.log\",\njob=~\"pm2.*\",\njob=\"systemd-journal\",\njob=\"jenkins-build\",\njob=~\"[a-z].*\""
   },
   { "name": "loki_filter", "label": "Loki Additional Filter" }
  ]
 },
 "panels": [
  {
   "title": "Systemd Units",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(node_systemd_unit_state{state=\"active\"})"
    },
    {
     "expr": "sum(node_systemd_unit_state{state=\"failed\"})"
    }
   ]
  },
  {
   "title": "Log Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate({$loki_query}[$__interval])"
    }
   ]
  },
  {
   "title": "Http Server Status",
   "type": "state-timeline",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "probe_success{instance=~\"127\\\\.0\\\\.0\\\\.1:.*\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "HTTP Request Time",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "probe_duration_seconds{instance=~\"127\\\\.0\\\\.0\\\\.1:.*\"}"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 29, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "{$loki_query}" }
   ]
  },
  {
   "title": "MemAvailable",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "node_memory_MemAvailable_bytes" },
    { "expr": "node_memory_MemTotal_bytes" }
   ]
  },
  {
   "title": "CPU Load",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "targets": [
    { "expr": "node_load1" },
    { "expr": "node_load5" }
   ]
  },
  {
   "title": "Filedescriptors allocated",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "targets": [
    { "expr": "node_filefd_allocated" }
   ]
  },
  {
   "title": "Diskspace Available",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{mountpoint=\"/\"}"
    },
    {
     "expr": "node_filesystem_size_bytes{mountpoint=\"/\"}"
    }
   ]
  },
  {
   "title": "Network Rx/Tx",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "node_network_receive_bytes_total{device=\"ens3\"}"
    },
    {
     "expr": "node_network_transmit_bytes_total{device=\"ens3\"}"
    }
   ]
  }
 ]
}