{
 "title": "staging",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Systemd Units",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(node_systemd_unit_state{state=\"active\"})"
    },
    {
     "expr": "sum(node_systemd_unit_state{state=\"failed\"})"
    }
   ]
  },
  {
   "title": "Http Server Status",
   "type": "state-timeline",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "probe_success{instance=~\"127\\\\.0\\\\.0\\\\.1:.*\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "HTTP Request Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 4 },
   "targets": [
    {
     "expr": "probe_duration_seconds{instance=~\"127\\\\.0\\\\.0\\\\.1:.*\"}"
    }
   ]
  },
  {
   "title": "MemAvailable",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "node_memory_MemAvailable_bytes" },
    { "expr": "node_memory_MemTotal_bytes" }
   ]
  },
  {
   "title": "Log Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "expr": "rate({host=\"timmi-staging\"}[$__interval])"
    }
   ]
  },
  {
   "title": "CPU Load",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    { "expr": "node_load15" },
    { "expr": "node_load5" }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 17, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "expr": "{host=\"timmi-staging\"}"
    }
   ]
  },
  {
   "title": "Filedescriptors allocated",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    { "expr": "node_filefd_allocated" }
   ]
  },
  {
   "title": "Network Rx/Tx",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "node_network_receive_bytes_total{device=\"ens3\"}"
    },
    {
     "expr": "node_network_transmit_bytes_total{device=\"ens3\"}"
    }
   ]
  },
  {
   "title": "Diskspace Available",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{mountpoint=\"/\"}"
    },
    {
     "expr": "node_filesystem_size_bytes{mountpoint=\"/\"}"
    }
   ]
  }
 ]
}