{
 "title": "Timmi Service Overview",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "Productive Alarm",
   "type": "timeseries",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(probe_success{instance=~\"https://timmitransport.de.*|.*productive.*\",job=~\"blackbox_timmi.*\"})"
    }
   ]
  },
  {
   "title": "Productive",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "probe_success{instance=~\"https://timmitransport.de.*\",job=~\"blackbox_timmi.*\"}",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "probe_success{instance=~\".*productive.*\",job=~\"blackbox_timmi.*\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Staging",
   "type": "state-timeline",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "probe_success{instance=~\".*staging.*\",job=~\"blackbox_timmi.*\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Test",
   "type": "state-timeline",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "probe_success{instance=~\".*test.*\",job=~\"blackbox_timmi.*\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}